net/Sample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Sample.Controllers {
    public class HomeController : Controller {

        [Route("")]
        public IActionResult Index() {
            return View();
        }

        [Route("SearchApi")]
        public IActionResult SearchApi() {
            return View();
        }

        [Route("GroupedList")]
        public IActionResult GroupedList() {
            return View();
        }

    }
}

net/Sample/Controllers/NorthwindController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Sample.Models;
using DevExtreme.AspNet.Data;
using Microsoft.AspNetCore.Cors;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;

namespace Sample.Controllers {

    [Route("nwind")]
    public class NorthwindController : Controller {
        NorthwindContext _nwind;

        public NorthwindController(NorthwindContext nwind) {
            _nwind = nwind;
        }

        [HttpGet("orders")]
        [EnableCors("AllowOrigin")]
        public async Task<IActionResult> Orders(DataSourceLoadOptions loadOptions) {
            var source = _nwind.Orders.Select(o => new {
                o.OrderId,
                o.CustomerId,
                o.OrderDate,
                o.Freight,
                o.ShipCountry,
                o.ShipRegion,
                o.ShipVia
            });

            loadOptions.PrimaryKey = new[] { "OrderId" };
            loadOptions.PaginateViaPrimaryKey = true;
            loadOptions.DefaultSort = "CustomerId";

            return Json(await DataSourceLoader.LoadAsync(source, loadOptions));
        }

        [HttpGet("order-details")]
        public async Task<IActionResult> OrderDetails(int orderId, DataSourceLoadOptions loadOptions) {
            var source = _nwind.OrderDetails
                .Where(i => i.OrderId == orderId)
                .Select(i => new {
                    Product = i.Product.ProductName,
                    Price = i.UnitPrice,
                    i.Quantity,
                    Sum = i.UnitPrice * i.Quantity
                });

            return Json(await DataSourceLoader.LoadAsync(source, loadOptions));
        }

        [HttpGet("customers-lookup")]
        public async Task<object> CustomersLookup(DataSourceLoadOptions loadOptions) {
            var source = _nwind.Customers
                .OrderBy(c => c.CompanyName)
                .Select(c => new {
                    Value = c.CustomerId,
                    Text = $"{c.CompanyName} ({c.Country})"
                });

            return Json(await DataSourceLoader.LoadAsync(source, loadOptions));
        }

        [HttpGet("shippers-lookup")]
        public async Task<object> ShippersLookup(DataSourceLoadOptions loadOptions) {
            var source = _nwind.Shippers
                .OrderBy(s => s.CompanyName)
                .Select(s => new {
                    Value = s.ShipperId,
                    Text = s.CompanyName
                });

            return Json(await DataSourceLoader.LoadAsync(source, loadOptions));
        }

        [HttpPut("update-order")]
        public async Task<IActionResult> UpdateOrder(int key, string values) {
            var order = await _nwind.Orders.FirstOrDefaultAsync(o => o.OrderId == key);
            if(order == null)
                return StatusCode(409, "Order not found");

            JsonConvert.PopulateObject(values, order);

            if(!TryValidateModel(order))
                return BadRequest(ModelState.ToFullErrorString());

            await _nwind.SaveChangesAsync();

            return Ok();
        }

        [HttpPost("insert-order")]
        public async Task<IActionResult> InsertOrder(string values) {
            var order = new Order();
            JsonConvert.PopulateObject(values, order);

            if(!TryValidateModel(order))
                return BadRequest(ModelState.ToFullErrorString());

            _nwind.Orders.Add(order);
            await _nwind.SaveChangesAsync();

            return Json(order.OrderId);
        }

        [HttpDelete("delete-order")]
        public async Task<IActionResult> DeleteOrder(int key) {
            var order = await _nwind.Orders.FirstOrDefaultAsync(o => o.OrderId == key);
            if(order == null)
                return StatusCode(409, "Order not found");

            _nwind.Orders.Remove(order);
            await _nwind.SaveChangesAsync();

            return Ok();
        }

        [HttpGet("products")]
        public async Task<IActionResult> Products(DataSourceLoadOptions loadOptions) {
            var source = _nwind.Products.Select(p => new {
                p.ProductId,
                p.ProductName,
                p.Category.CategoryName,
                p.UnitPrice
            });

            return Json(await DataSourceLoader.LoadAsync(source, loadOptions));
        }

    }
}

net/Sample/Views/Home/GroupedList.cshtml
@{
    Layout = "~/Views/_Layout.cshtml";
}

<div id="list"></div>
<script>
    $(function() {
        $("#list").dxList({
            dataSource: {
                store: DevExpress.data.AspNet.createStore({
                    loadUrl: "@Url.Action("Products", "Northwind")"
                }),
                group: "categoryName",
                sort: "productName",
                paginate: true,
                pageSize: 1 // group
            },
            grouped: true,
            itemTemplate: function(product) {
                return product.productName;
            }
        });
    });
</script>

net/Sample/Views/Home/Index.cshtml
@{
    Layout = "~/Views/_Layout.cshtml";
}
<div id="grid"></div>
<script>
    $(function() {
        $("#grid").dxDataGrid({

            dataSource: DevExpress.data.AspNet.createStore({
                key: "orderId",
                loadUrl: "@Url.Action("Orders", "Northwind")",
                updateUrl: "@Url.Action("UpdateOrder", "Northwind")",
                insertUrl: "@Url.Action("InsertOrder", "Northwind")",
                deleteUrl: "@Url.Action("DeleteOrder", "Northwind")",

                onBeforeSend: function(operation, ajaxSettings) {
                    // operation - any of "load", "update", "insert", "delete"
                    // ajaxSettings - http://api.jquery.com/jquery.ajax/
                }
            }),

            columns: [
                {
                    dataField: "customerId",
                    caption: "Customer",
                    lookup: {
                        valueExpr: "value",
                        displayExpr: "text",
                        dataSource: DevExpress.data.AspNet.createStore({
                            key: "value",
                            loadUrl: "@Url.Action("CustomersLookup", "Northwind")"
                        })
                    }
                },
                {
                    dataField: "orderDate",
                    dataType: "date",
                    headerFilter: {
                        groupInterval: "quarter"
                    }
                },
                {
                    dataField: "freight",
                    headerFilter: {
                        groupInterval: 100
                    }
                },
                "shipCountry",
                "shipRegion",
                {
                    dataField: "shipVia",
                    lookup: {
                        valueExpr: "value",
                        displayExpr: "text",
                        dataSource: DevExpress.data.AspNet.createStore({
                            key: "value",
                            loadUrl: "@Url.Action("ShippersLookup", "Northwind")"
                        })
                    }
                }
            ],

            groupPanel: { visible: true },
            filterRow: { visible: true },
            headerFilter: { visible: true },
            editing: {
                allowUpdating: true,
                allowAdding: true,
                allowDeleting: true
            },
            remoteOperations: true,
            grouping: {
                autoExpandAll: false
            },
            summary: {
                totalItems: [
                    { column: "freight", summaryType: "sum" }
                ],
                groupItems: [
                    { column: "freight", summaryType: "sum" },
                    { summaryType: "count" }
                ]
            },

            masterDetail: {
                enabled: true,
                template: function(container, options) {
                    $("<div>")
                        .dxDataGrid({
                            dataSource: DevExpress.data.AspNet.createStore({
                                loadUrl: "@Url.Action("OrderDetails", "Northwind")",
                                loadParams: { orderId: options.data.orderId }
                            }),
                            remoteOperations: true,
                            showBorders: true
                        })
                        .appendTo(container);
                }
            }
        });
    });
</script>

net/Sample/Views/Home/SearchApi.cshtml
@{
    Layout = "~/Views/_Layout.cshtml";
}

<div id="lookup"></div>
<script>
    $(function() {
        $("#lookup").dxLookup({
            dataSource: DevExpress.data.AspNet.createStore({
                loadUrl: "@Url.Action("Products", "Northwind")"
            }),
            valueExpr: "productId",
            displayExpr: "productName",
            searchEnabled: true
        });
    });
</script>